### ISSUE TITLE
\ (バックスラッシュ) が自動でエスケープされる （ご教授ください）

### ISSUE THREAD

**Issue by forno** [rhysd/wandbox-vim#9]
手側の環境の問題だと思うので大変恐縮なのですが、以下のように\が自動でエスケープされてしまいます。

![input](https://user-images.githubusercontent.com/11057257/34000079-9f271322-e12f-11e7-9af6-a4461e27ad0d.png)
![result](https://user-images.githubusercontent.com/11057257/34000085-a0fbf104-e12f-11e7-81c6-4009f95b2e04.png)

また、帰ってくる結果も正常に表示できないケースがあるようです。

![warning](https://user-images.githubusercontent.com/11057257/34000253-10448fda-e130-11e7-8366-3c32940613b1.png)

# 環境
- OS: Ubuntu 16.04 server
  * Note: gnome desktop をインストールして使用
- Vim: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 12 2017 05:25:06) 適用済パッチ: 1-1385
  * https://github.com/vim/vim.git からpythonとpython3を有効にしてソースからコンパイル。
- Install method:
  * $HOME/.vim/pack/wandbox/start/ 以下に git clone https://github/rhysd/wandbox-vim.git
  * Vim の packages 機能で使用しています。

初歩的かつ、どちらかというとVimの問題で wandbox-vim の問題ではなさそうなのですが、
私が調べた限りでは解決方法がわからなかったため、ご教授いただけましたら幸いです。

**Comment by rhysd** [comment]
報告ありがとうございます．以前はそんなことなかったはずなんですが，エスケープが wandbox 側で行われるようになっているらしく，2重にエスケープされていました．71c97b1 で修正しました．

また，返ってくる結果に `^[[0m` のような文字が入ってしまうのは ANSI のカラーシーケンスがそのまま入ってきているからですね… さっとは対応でき無さそうなので，とりあえずコンパイラのオプションに `-fno-color-diagnostics` あたりを足しておくと回避できると思います．

**Comment by forno** [comment]
汎用的な内容だったようで幸いです。

カラーシーケンスについてもご意見いただけましたこと、ありがとうございます。
